export type PageSpec = {
  id: string;
  path: string;
  name: string;
  role: "portal" | "admin" | "common";
  fidelity: "高保真" | "结构与状态" | "评审工具";
  requirements: string[];
  states: string[];
  openRules: string[];
  nav?: boolean;
};
const commonStates = [
  "默认",
  "加载中",
  "无数据",
  "网络失败",
  "无权限",
  "长文本",
];
function page(
  id: string,
  path: string,
  name: string,
  role: PageSpec["role"],
  fidelity: PageSpec["fidelity"],
  requirements: string[],
  openRules: string[],
  nav = false,
  states = commonStates,
): PageSpec {
  return {
    id,
    path: `/prototype/${path}`,
    name,
    role,
    fidelity,
    requirements,
    openRules,
    nav,
    states,
  };
}
export const catalog: PageSpec[] = [
  page("G01", "index", "页面与状态索引", "common", "评审工具", [], [], false, [
    "默认",
  ]),
  page(
    "G02",
    "login",
    "登录",
    "common",
    "结构与状态",
    ["AUTH"],
    ["D02 注册与成员权限"],
    false,
    ["默认", "账户错误"],
  ),
  page(
    "G03",
    "reset-password",
    "找回密码",
    "common",
    "结构与状态",
    ["AUTH"],
    ["D02 注册与成员权限"],
    false,
    ["默认", "错误", "申请说明"],
  ),
  page(
    "P01",
    "portal/orders",
    "我的订单",
    "portal",
    "高保真",
    ["ORD", "TRK"],
    ["D10 审核与撤单规则"],
    true,
  ),
  page(
    "P02",
    "portal/inquiry",
    "新建询价",
    "portal",
    "高保真",
    ["INQ", "ADR"],
    ["D01 首发运输范围", "D05 ERP 规则"],
    true,
    ["默认", "字段错误", "长文本", "草稿恢复"],
  ),
  page(
    "P03",
    "portal/quotes",
    "报价比较",
    "portal",
    "高保真",
    ["QUO"],
    ["D04 承运商接入", "D09 定价与有效期"],
    false,
    ["默认", "加载中", "无报价", "部分失败", "网络失败", "报价过期"],
  ),
  page(
    "P04",
    "portal/confirm",
    "确认下单",
    "portal",
    "高保真",
    ["ORD", "QUO"],
    ["D06 扣款规则", "D10 审核规则"],
    false,
    ["默认", "提交中", "报价失效"],
  ),
  page(
    "P05",
    "portal/orders/TF-261004-1078",
    "订单详情",
    "portal",
    "高保真",
    ["ORD", "TRK"],
    ["D11 附件与事件来源"],
    false,
  ),
  page(
    "P06",
    "portal/inquiries",
    "询价记录",
    "portal",
    "结构与状态",
    ["INQ", "QUO"],
    ["D09 报价保存期限"],
    true,
  ),
  page(
    "P07",
    "portal/addresses",
    "地址簿",
    "portal",
    "结构与状态",
    ["ADR"],
    ["D02 私有地址访问范围"],
    true,
  ),
  page(
    "P08",
    "portal/finance",
    "资金与账单",
    "portal",
    "结构与状态",
    ["FIN"],
    ["D06 预付或月结", "D07 费用调整", "D08 充值与提现"],
    true,
  ),
  page(
    "P09",
    "portal/tickets",
    "服务工单",
    "portal",
    "结构与状态",
    ["CLM"],
    ["D12 售后与赔付政策"],
    true,
  ),
  page(
    "A01",
    "admin/orders",
    "订单工作台",
    "admin",
    "高保真",
    ["ORD"],
    ["D10 审核与人工核实权限"],
    true,
  ),
  page(
    "A02",
    "admin/orders/TF-261004-1078",
    "订单处理详情",
    "admin",
    "高保真",
    ["ORD", "TRK"],
    ["D04 承运商重试", "D10 人工处理规则"],
    false,
    ["默认", "提交中", "超时待确认", "失败", "接单"],
  ),
  page(
    "A03",
    "admin/customers",
    "客户与成员",
    "admin",
    "结构与状态",
    ["CUS", "AUTH"],
    ["D02 权限与邀请", "D03 账户冻结"],
    true,
  ),
  page(
    "A04",
    "admin/warehouses",
    "仓库与地址",
    "admin",
    "结构与状态",
    ["ADR"],
    ["D01 服务范围", "D05 外仓来源"],
    true,
  ),
  page(
    "A05",
    "admin/carriers",
    "承运商",
    "admin",
    "结构与状态",
    ["CAR"],
    ["D04 API 与人工承运商"],
    true,
  ),
  page(
    "A06",
    "admin/settlement",
    "结算中心",
    "admin",
    "结构与状态",
    ["FIN"],
    ["D06 信用额度", "D07 应收应付与调整"],
    true,
  ),
  page(
    "A07",
    "admin/tickets",
    "售后工单",
    "admin",
    "结构与状态",
    ["CLM"],
    ["D12 工单与赔付分离"],
    true,
  ),
  page(
    "A08",
    "admin/reports",
    "运营报表",
    "admin",
    "结构与状态",
    ["RPT"],
    ["D13 容量和统计口径"],
    true,
  ),
];
